### ISSUE TITLE
BUG - Output table not working

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/imap-data-access#29]
### ## Description of the issue

When running query, the output table does not work. The `--output-format json` option still works.

### Steps to reproduce the issue

imap-data-access query --instrument mag --data-level l0

### Code Snippet:

```python
❯ imap-data-access query --instrument mag --data-level l0
Found [4] matching files
---------------------------------------------------------------------------------------------------------------|
Instrument|Data Level|Descriptor|Start Date|Repointing|Version|Filename                                          |
---------------------------------------------------------------------------------------------------------------|
Traceback (most recent call last):
  File "/Users/maha7656/Documents/code/imap/venv/bin/imap-data-access", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/maha7656/Documents/code/imap/venv/lib/python3.11/site-packages/imap_data_access/cli.py", line 292, in main
    args.func(args)
  File "/Users/maha7656/Documents/code/imap/venv/lib/python3.11/site-packages/imap_data_access/cli.py", line 114, in _query_parser
    _print_query_results_table(query_results)
  File "/Users/maha7656/Documents/code/imap/venv/lib/python3.11/site-packages/imap_data_access/cli.py", line 79, in _print_query_results_table
    print(format_string.format(*values))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported format string passed to NoneType.__format__
```

### Expected behavior (What should happen)

Print table

### Actual behavior (What does happen)

Error

**Comment by greglucas** [comment]
This was fixed by https://github.com/IMAP-Science-Operations-Center/imap-data-access/pull/27 and just hasn't been released yet. I'll try and push out another release soon with some other items as well. But this does work if you use main currently.

**Comment by maxinelasp** [comment]
@greglucas Ah, my bad, I didn't connect that with the other ticket! It would be great to release this soon, MAG asked about using it

**Comment by greglucas** [comment]
No problem at all! OK, maybe we can just make another release after your other update is fixed (PR incoming).
