### ISSUE TITLE
Add an option to the API to retrieve the latest version of a given file

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/imap-data-access#38]
### Summary

It would be nice to be able to pass in a "latest" flag or "latest" to the version, and have the query part of the API retrieve only the highest version number that matches the other requirements. This would be useful for ancillary files as well.

Note: This could be a good student ticket for exposure to the API and argparse.

### Requirements

The more specific the better.
  - [ ] Add a "latest" option to the "--version" input
  - [ ] Have the query with that flag only return the highest version numbers that match the rest of the requirements.

**Comment by krishpy99** [comment]
Hi, I am new to open source and interested in working on this issue. How do I get assigned?
