### ISSUE TITLE
User testing

### ISSUE THREAD

**Issue by bourque** [IMAP-Science-Operations-Center/imap-data-access#40]
It would be a useful exercise for a user to extensively test this command line utility and identify any bugs or any areas that could use improvement.

A summer student would be well suited for this since they have not been involved in the development process of this tool yet. It would be a good way to learn how to use this utility.

- Are the installation instructions clear?
- Are the help docs clear?
- Are you able to upload a L0 `.pkts` file?
- Are you able to upload a L1 CDF file?
- When trying to upload an invalid file, are the error/warning messages that are thrown clear?
- Are you able to run a successful query? Do any combinations of query parameters cause something to break?
- Is the resulting output table formatted correctly?
- Are you able to download a file that is listed as available in a query?
- When trying to download a file that doesn't exist, are the error/warning messages that are thrown clear?

**Comment by bourque** [comment]
@daralynnrhode @anamanica Feel free to leave a comment here with whatever you discovered in your imap-data-access journey. We can then open up new GitHub issues for things to fix/clarify/change based on what you found.

**Comment by anamanica** [comment]
Hi there! Here are @daralynnrhode and I's comments!

- Ticket Questions:
    - Are the Installation instructions clear?
        - For the most part, pretty good! The only issues I ran into involved the version 
           of pip I had installed. pip3 didn’t work, so I had to update the version of pip                                  
           before I could download the package. 

    - Are the docs clear?
        - The docs are very nice. I do have some suggestions on things that could be 
            added/changed, but I think that is more to do with the query -h feature. 
        - Clarify that ‘l0, l1, etc” is a lowercase L, and not an uppercase “I.”
        - In the download section, note that your working directory will be established as 
           the default directory. I.e, the data directory will automatically be placed here. 
           Suggest user to be in /Desktop working directory. 
            - To a similar point, explain config better for the purpose of changing working 
               directory.
        - In the upload section, note that your working directory must be one level above 
           the file path of the /data directory (where your files must be stored) for 
           uploads to succeed. 
        - At the beginning, make note of the troubleshooting section further down. We 
           didn’t know it was there when starting out testing.
        - Make it more clear that when downloading a file, it will create folders for each 
          bit of information in the file name.

    - Are you able to upload a L0 .pkts file?
        - Yes! In fact, I may be able to upload too much. I was able to create an empty 
           CDF file with the correct naming conventions, and the program took it. I was 
           also able to upload a CDF file with python script code in it.
        - To upload, make sure you are in one directory above the data directory. 
           Perhaps add to docs?

    - Are you able to upload a L1 CDF file?
        - Yes, this works just fine. Same process of uploading l0 files.

    - When trying to upload an invalid file, are the error/warning messages that are 
       thrown clear?
        - Yes

    - Are you able to run a successful query? Do any combinations of query 
       parameters cause something to break?
        - Putting in an incorrect data level throws errors. Also, using a capital “L” instead 
           of a lowercase “l” throws the same error: 
		    	HTTP Error: 502 - Bad Gateway
		    	Server Message: {"message": "Internal server error"} 
        - Putting an incorrect —start-date query throws errors. You get the same 502 
          error. 
        - It looks like —end-date is not recognized as a query yet. I can put in anything I 
           want for end date, like “ana, 9, 20240000, etc.” and it does not filter files, or 
           throw errors.
        - Doesn’t look like —repointing is helpful as none of the test files have repointing 
           information.  Uploading strings throws errors, but that is all I could test. Also, 
           the format of this section in the -h query menu has inconsistent formatting. 
        - Searching for —extension py throws error 502. -h does specify only .cfd and 
          .pkts filetype, but perhaps a warning message could be displayed instead of an 
          error.
        - Add an option to search by filename. Its tedious to have to input each 
          parameter individually.

    - Is the resulting output table formatted correctly?
        - If the descriptor name is too long, then everything gets off-kilter. Look at all  
           codice files to show this.

    - Are you able to download a file that is listed as available in a query?
        - Yep! This works with l0 and l1a data well.

    - When trying to download a file that doesn’t exist, are the error/warning messages 
       that are thrown clear?
        - I had success downloading [imap_codice_l0_lo-sw-angular_20240429_v001.pkts] but there only exists 
           [imap_codice_l0_lo-sw-angular_20240610_v001.pkts] and [imap_codice_l1a_lo-sw- 
           angular_20240429_v001.cdf]. However, downloading other files that don’t exist by randomly modifying 
           things doesn’t not work. It throws error 404. So, it seems this problem only takes place when you have files 
           that have the exact same EVERYTHING accept for file extension and date. You can download the lower data 
           level file at the higher data level’s date. However, I wasn’t able to replicate this by downloading CDF files I 
           myself created.
    - Other notes:
        - In the help menu, optional arguments throw errors (internal server error).

**Comment by bourque** [comment]
@anamanica @daralynnrhode This is great! Thank you for the thorough review and explanations. From this, I think we can make a few new issues:

- A general 'update the documentation' issue to address your points on some of the area of the documentation being unclear
- An issue for addressing the 502 errors -- more informative error messages should be thrown in these cases
- An issue to get the `--end-date` parameter working
- An issue to fix the formatting issues you see when using the `-h` flag
- An issue for adding support for providing a filename as a search option
- An issue to fix the output table for long descriptors

I don't quite follow the issue you were seeing when downloading files that don't exist, but it sounds to me like it is failing gracefully? If you feel something needs to be changed here, feel free to open an issue for that too!

I think we can address the `--repointing` issue sometime later -- the SDC is still trying to figure out how this is going to work.

@greglucas Since you are kind of the 'owner' of this code/repo, I just wanted to run these by you too. Are all of these worth doing? Do you have anything to add? Thanks!

**Comment by greglucas** [comment]
I hope you all feel empowered to add / update things as you see fit here, so please do make issues you think will help :)

I agree all of those things sound like good ideas, just one tidbit to add here that might help point in the right direction.
> - An issue for addressing the 502 errors -- more informative error messages should be thrown in these cases

Anything with 502 will need to be addressed in the AWS Lambdas most likely. Although it might be that the update needs to be in the path validation area which is actually in this repository.

**Comment by bourque** [comment]
Nice work on this @daralynnrhode and @anamanica, and thanks for opening up new issues for the things you found! I am closing this issue now.
