### ISSUE TITLE
Remove the requirement to upload from a specific data folder structure

### ISSUE THREAD

**Issue by greglucas** [IMAP-Science-Operations-Center/imap-data-access#41]
### Summary

It would be nice to have the ability to upload data files from any directory structure and not require the command to be run from a specific current working directory + data/ folder combination. It is currently confusing where you need to run the cli from, so removing all folder path requirements on the upload would be helpful.

cc @vmartinez-cu @tech3371, feel free to add clarifications to this that would help

### Requirements

The more specific the better.
  - [ ] Remove upload folder path requirement
  - [ ] Should be able to take in full path to folder `/root/path/to/file.txt` and `path/to/file.txt` (if you're currently in `/root`)

**Comment by vmartinez-cu** [comment]
This looks good. I think it would be nice too if it defaults to the current working directory if only a filename is given. It's the `data/` part that is a little too restrictive
