### ISSUE TITLE
BUG : --end-date query parameter not working

### ISSUE THREAD

**Issue by anamanica** [IMAP-Science-Operations-Center/imap-data-access#50]
### Description of the issue

No `end-date `is specified with each uploaded file, and this parameter does not work to filter files. You can enter  any string, date, etc without throwing errors. Either get rid of the `end-date` parameter all together, or implement it. 

### Steps to reproduce the issue

Run `imap-data-access query --end-date <anything>` to see --end-date is not accepted as a parameter.

### Expected behavior (What should happen)

Running `imap-data-access query --end-date <anything>` should work to narrow down files presented after the user query.

### Actual behavior (What does happen)

`--end-date` is not accepted as a parameter. It doesn't do anything.

### Code Snippet:

```python
Code
```

### Additional notes, affected areas, and suggested fixes

If `end-date`*is* implemented, I feel that and end-date section should be added to file naming conventions.

**Comment by mfacchinelli** [comment]
Could it be the same as #47?
